### ISSUE TITLE
Предикаты в bemhtml перевести в like CSS селекторы

### ISSUE THREAD

**Issue by banzalik** [bem/bem-bl#313]
Сейчас:

``` css
block b-menu, elem item, elemMod state current {
   tag: 'span'
}
```

Хочется:

``` css
block.b-menu elem.item[state="current"] {
  tag: 'span'
}
```

Кроме того CSS селекторы сильно мощнее, чем предикаты в bemhtml, если использовать их во весь рост, то можно сильно упростить тело шаблонов.
